# Generated by Django 3.2.9 on 2021-11-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211127_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dishcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='static/media', verbose_name='Картинка')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dishcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
